spring:
  application:
    name: auth-api
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://localhost:3306/auth?useSSL=false&serverTimezone=UTC
    username: root
    password: root



